"""
================================================================================
  generalization_check_synthetic.py
  ────────────────────────────────────────────────────────────────────────────
  Scores the frozen production ensemble (src.fraud_model.score() — the same
  function main.py's /predict endpoint calls, XGBoost + rules + LightLR
  combined) against synthetic_grounded_dataset.csv, the independently-drawn
  FULL-40-feature dataset built by generate_grounded_synthetic_dataset.py.

  This is the complement to GENERALIZATION_CHECK.md's two external datasets:
  those carried only 6/40 (15.0%) and 2/40 (5.0%) of the model's honest
  feature vector, so a bad result there could always be blamed on "85% of
  the input is missing." This dataset carries all 40 features, generated by
  a genuinely different process (different seed, different generative
  structure, different fraud-label correlation mechanism — see
  generate_grounded_synthetic_dataset.py's module docstring). A bad result
  HERE cannot be blamed on missing features — it would point at something
  deeper: overfitting to the training pipeline's specific generation
  process rather than to generalizable fraud patterns.

  No retraining, no fine-tuning, no threshold recalibration — same rule as
  both prior checks. Frozen model, frozen preprocessor, frozen threshold
  (0.40), frozen light_lr.pkl, all loaded exactly as load_artefacts() does
  at production startup.

  Run
  ───
      venv\\Scripts\\python.exe generalization_check_synthetic.py
================================================================================
"""

import io
import logging
import os
import sys
import time
import warnings

warnings.filterwarnings("ignore", category=UserWarning, module="sklearn")
if __name__ == "__main__":
    # Guarded: unconditional reassignment at import time breaks pytest's
    # capture mechanism for anything that imports this module. See
    # ood_generalization_remediation.py's identical fix for the confirmed
    # failure mode.
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

# src/fraud_model.py's _score_light_lr() does `float(txn_dict.get(key, 0.0))`
# — .get()'s default only fires when the KEY IS ABSENT, not when the key is
# present with value None. This dataset intentionally carries ~2% None
# values for amount_deviation_score / transaction_velocity (matching
# data_dictionary.csv's documented "~2% missing intentionally"), sent as
# real keys with a null value — not omitted keys — because that is what the
# training data's own missingness pattern represents. That means
# _score_light_lr() throws on those rows and fraud_model.score() logs a
# WARNING for each ( ~1,000+ times across 25,000 rows). This is a genuine,
# reportable robustness gap in the frozen scorer (see SYNTHETIC_GROUNDING.md
# side-findings) — logging is only quieted here for readable script output,
# the underlying warnings are still counted below via NaN light_lr_score.
logging.getLogger("paysense.ensemble").setLevel(logging.ERROR)

import numpy as np
import pandas as pd
from sklearn.metrics import (
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    classification_report,
)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "src"))

from src import fraud_model  # noqa: E402

DATASET_CSV = os.path.join(BASE_DIR, "synthetic_grounded_dataset.csv")


def main():
    print("Loading production ensemble artefacts via load_artefacts() "
          "(same call main.py makes at startup) ...")
    state = fraud_model.load_artefacts()
    print(f"Active scorers: {state.active_scorers}")
    assert "paysense" in state.active_scorers, "PaySense XGBoost artefact must be loaded."
    assert "light_lr" in state.active_scorers, (
        "light_lr is not active — artefacts/light_lr.pkl must exist and be "
        "loaded from disk for this check to actually test the full ensemble."
    )
    threshold = state.ps_threshold
    print(f"Frozen threshold: {threshold}")

    if not os.path.exists(DATASET_CSV):
        raise FileNotFoundError(
            f"{DATASET_CSV} not found — run generate_grounded_synthetic_dataset.py first."
        )

    df = pd.read_csv(DATASET_CSV)
    y = df["is_fraud"].astype(int).to_numpy()
    n_fraud = int(y.sum())
    print(f"\nDataset: synthetic_grounded_dataset.csv — {len(df):,} rows, "
          f"{n_fraud:,} fraud ({n_fraud/len(df)*100:.2f}%)")

    # All 40 model features are present (no honest-mapping subset needed —
    # that is the entire point of this check). Build one dict per row exactly
    # as a real /predict caller sending the full feature vector would.
    records = df.to_dict(orient="records")
    print(f"\nScoring {len(records):,} rows through fraud_model.score() "
          f"(full ensemble: XGBoost + rules + LightLR) ...")
    t0 = time.time()

    ensemble_scores = np.empty(len(records), dtype=float)
    paysense_scores = np.full(len(records), np.nan, dtype=float)
    lr_scores = np.full(len(records), np.nan, dtype=float)
    rules_scores = np.empty(len(records), dtype=float)
    weights_seen = set()

    for i, rec in enumerate(records):
        clean = {k: (None if isinstance(v, float) and np.isnan(v) else v) for k, v in rec.items()}
        result = fraud_model.score(clean)
        ensemble_scores[i] = result.ensemble_score
        if result.paysense_score is not None:
            paysense_scores[i] = result.paysense_score
        if result.light_lr_score is not None:
            lr_scores[i] = result.light_lr_score
        rules_scores[i] = result.rules_score
        weights_seen.add(tuple(sorted(result.weights_used.items())))
        if i and i % 5000 == 0:
            print(f"  ... {i:,} / {len(records):,} rows scored "
                  f"({time.time()-t0:.1f}s elapsed)")

    elapsed = time.time() - t0
    print(f"Scored {len(records):,} rows in {elapsed:.1f}s "
          f"({len(records)/max(elapsed,1e-9):.0f} rows/sec)")
    print(f"Distinct weights_used maps seen across all rows: {weights_seen}")
    n_lr_null_crash = int(np.isnan(lr_scores).sum())
    print(f"Rows where LightLR silently failed (explicit None in one of its "
          f"5 features, not an absent key — see script header): "
          f"{n_lr_null_crash:,} / {len(records):,} "
          f"({n_lr_null_crash/len(records)*100:.2f}%)")

    preds = (ensemble_scores >= threshold).astype(int)

    roc_auc = roc_auc_score(y, ensemble_scores)
    pr_auc = average_precision_score(y, ensemble_scores)
    cm = confusion_matrix(y, preds)
    report = classification_report(y, preds, digits=4, zero_division=0)

    # Raw XGBoost-only, for the same side-by-side comparison the ensemble
    # check ran against Dataset 1.
    roc_auc_raw = roc_auc_score(y, paysense_scores)
    pr_auc_raw = average_precision_score(y, paysense_scores)
    preds_raw = (paysense_scores >= threshold).astype(int)
    cm_raw = confusion_matrix(y, preds_raw)

    print("\n" + "=" * 78)
    print("  FULL ENSEMBLE vs RAW XGBOOST — synthetic_grounded_dataset.csv (full 40 features)")
    print("=" * 78)
    print(f"  Rows                          : {len(df):,}")
    print(f"  Fraud rate                    : {n_fraud/len(df)*100:.2f}%")
    print(f"  {'Metric':<32}{'Raw XGBoost':>15}{'Full ensemble':>15}")
    print(f"  {'-'*32}{'-'*15}{'-'*15}")
    print(f"  {'ROC-AUC':<32}{roc_auc_raw:>15.4f}{roc_auc:>15.4f}")
    print(f"  {'PR-AUC':<32}{pr_auc_raw:>15.4f}{pr_auc:>15.4f}")
    print(f"  {'Max predicted score':<32}{np.nanmax(paysense_scores):>15.4f}{ensemble_scores.max():>15.4f}")
    print(f"\n  Confusion matrix (full ensemble) @ threshold {threshold} [[TN FP][FN TP]]:")
    print(f"      {cm.tolist()}")
    print(f"  Confusion matrix (raw XGBoost) @ threshold {threshold} [[TN FP][FN TP]]:")
    print(f"      {cm_raw.tolist()}")
    print(f"\n  Min/mean/max paysense_score   : {np.nanmin(paysense_scores):.4f} / "
          f"{np.nanmean(paysense_scores):.4f} / {np.nanmax(paysense_scores):.4f}")
    print(f"  Min/mean/max light_lr_score   : {np.nanmin(lr_scores):.4f} / "
          f"{np.nanmean(lr_scores):.4f} / {np.nanmax(lr_scores):.4f}")
    print(f"  Min/mean/max rules_score      : {rules_scores.min():.4f} / "
          f"{rules_scores.mean():.4f} / {rules_scores.max():.4f}")
    print(f"\n{report}")

    print("=" * 78)
    print("  SIDE-BY-SIDE: this check vs. GENERALIZATION_CHECK.md's two external datasets")
    print("=" * 78)
    print(f"  {'Metric':<32}{'Dataset 1 (6/40 feat)':>22}{'Dataset 3 (2/40 feat)':>22}{'This (40/40 feat)':>18}")
    print(f"  {'-'*32}{'-'*22}{'-'*22}{'-'*18}")
    print(f"  {'ROC-AUC (full ensemble)':<32}{0.8107:>22.4f}{'n/a (raw only)':>22}{roc_auc:>18.4f}")
    print(f"  {'PR-AUC (full ensemble)':<32}{0.4136:>22.4f}{'n/a':>22}{pr_auc:>18.4f}")
    print(f"  {'Recall @ 0.40 threshold':<32}{'0/701 = 0.0%':>22}{'0/64 = 0.0%':>22}"
          f"{f'{cm[1,1]}/{n_fraud} = {cm[1,1]/max(n_fraud,1)*100:.1f}%':>18}")

    return {
        "roc_auc": roc_auc, "pr_auc": pr_auc, "confusion_matrix": cm.tolist(),
        "roc_auc_raw": roc_auc_raw, "pr_auc_raw": pr_auc_raw,
        "n": len(y), "n_fraud": n_fraud,
        "max_ensemble_score": float(ensemble_scores.max()),
    }


if __name__ == "__main__":
    main()
