"""
================================================================================
  PaySense — OOD Generalization Remediation Experiment
  ────────────────────────────────────────────────────────────────────────────
  Question: SYNTHETIC_GROUNDING.md found the frozen model ranks WORSE
  (ROC-AUC ~0.70) on a full-40-feature synthetic dataset generated by a
  genuinely different process than it does on GENERALIZATION_CHECK.md's
  Dataset 1, which supplies only 6/40 features but is drawn from a real UPI
  transaction stream (ROC-AUC ~0.79 ensemble). Feature completeness cannot
  explain that gap; SYNTHETIC_GROUNDING.md's own conclusion is that the model
  has partially overfit to paysense_pipeline.py's specific anchor/supplement
  correlation structure -- not just to which fields happen to be populated.

  This script tests one falsifiable remediation: does training on a BLEND of
  the original pipeline's data plus a differently-structured generative
  process reduce that overfitting, measured on data never used in training?
  A second, cheaper control (heavier regularization on the ORIGINAL data
  only) tests whether this is a regularization problem rather than (or in
  addition to) a data-diversity problem.

  LEAKAGE DISCIPLINE (the main risk in this experiment)
  ────────────────────────────────────────────────────────────────────────────
  generate_grounded_synthetic_dataset.py's on-disk synthetic_grounded_dataset
  .csv (SEED=918273, 25,000 rows) was generated for SYNTHETIC_GROUNDING.md
  and has never been trained on by anything. This script:
    1. Generates a SECOND, independently-seeded synthetic dataset
       (SEED=445566, 12,000 rows) via the *same* generator function --
       different seed, same generative structure/weights as the 918273 set,
       but a disjoint random draw -- and blends ONLY this one into training
       (Variant A).
    2. Keeps the EXISTING seed-918273 dataset entirely unseen by training and
       uses it as the held-out synthetic evaluation set for all three models
       (baseline, A, B). Its baseline ensemble numbers are cited verbatim
       from SYNTHETIC_GROUNDING.md (already computed against that exact file
       by generalization_check_synthetic.py) rather than re-run.
    3. Never touches paysense_master_dataset.csv's TEST partition (the
       canonical 20% / 6,000-row split) with anything from either synthetic
       dataset -- both the blend and the held-out set are entirely separate
       from that split, and the test partition itself is reproduced with the
       exact random_state=42 stratified split paysense_phase3.py uses.
    4. The two real external datasets (GENERALIZATION_CHECK.md Datasets 1 and
       3) are never trained on by anything in this project -- they don't even
       carry the full 40-feature schema, so training on them isn't possible,
       let alone tempting.

  A regression test (tests/test_ood_generalization_remediation.py) locks in
  that the blend seed (445566) and the held-out eval seed (918273) are
  verifiably different, and that no row from the held-out CSV appears in the
  blend CSV (by transaction_id, which is seed-namespaced: SGT0000000 vs a
  disjoint id space per seed).

  NO CHANGES to artefacts/paysense_model.pkl, paysense_preprocessor.pkl, or
  paysense_threshold.pkl happen anywhere in this script. All new artifacts
  are saved under new filenames and are not wired into src/fraud_model.py or
  main.py -- to score them through the real ensemble path this script
  monkeypatches the in-memory fraud_model._state object only (never touches
  the module's file-path constants or any file on disk).

  Outputs:
    - synthetic_grounded_dataset_seed445566_blend.csv   (blend-only data)
    - artefacts/paysense_model_blended_training.pkl        (Variant A model)
    - artefacts/paysense_preprocessor_blended_training.pkl (Variant A preprocessor)
    - artefacts/paysense_model_regularized.pkl              (Variant B model)
    - ood_generalization_remediation_results.json          (all numbers)

  Run
  ───
      venv\\Scripts\\python.exe ood_generalization_remediation.py
================================================================================
"""

import io
import json
import logging
import os
import sys
import time
import warnings

warnings.filterwarnings("ignore")
warnings.filterwarnings("ignore", category=UserWarning, module="sklearn")
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
logging.getLogger("paysense.ensemble").setLevel(logging.ERROR)

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    average_precision_score,
    confusion_matrix,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, "src"))

import generate_grounded_synthetic_dataset as gen_synth  # noqa: E402
from generalization_check import load_dataset_1, load_dataset_3  # noqa: E402
from src import fraud_model  # noqa: E402

ARTEFACTS_DIR = os.path.join(BASE_DIR, "artefacts")
MASTER_CSV = os.path.join(BASE_DIR, "paysense_master_dataset.csv")
HELD_OUT_SYNTH_CSV = os.path.join(BASE_DIR, "synthetic_grounded_dataset.csv")  # seed 918273
BLEND_SYNTH_CSV = os.path.join(BASE_DIR, "synthetic_grounded_dataset_seed445566_blend.csv")

RANDOM_STATE = 42
BLEND_SEED = 445566
HELD_OUT_SEED = 918273  # the existing on-disk dataset -- verified below, never trained on
BLEND_N_TXN = 12000

DROP_COLS = [
    "transaction_id", "user_id", "receiver_id", "timestamp", "date",
    "data_source", "user_kyc_status", "status", "usr_home_city",
]
TARGET = "is_fraud"
DEPLOYED_THRESHOLD = 0.30  # current frozen threshold -- used for every model so
                           # cross-model comparisons are apples-to-apples, not
                           # each variant graded against its own optimal cutoff.

BASE_XGB_KWARGS = dict(
    n_estimators=400,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.80,
    colsample_bytree=0.80,
    min_child_weight=10,
    gamma=0.10,
    scale_pos_weight=1,
    reg_alpha=0.05,
    reg_lambda=1.50,
    eval_metric="aucpr",
    tree_method="hist",
    random_state=RANDOM_STATE,
    n_jobs=-1,
    verbosity=0,
)

# Variant B: cheaper regularization control, 3 changes only (not a grid search).
VARIANT_B_XGB_OVERRIDES = dict(
    max_depth=3,          # shallower trees -- less capacity to fit noise
    reg_lambda=3.0,        # 2x L2 penalty
    min_child_weight=20,   # 2x -- requires more evidence per leaf split
)

BEHAVIORAL_FEATURES = ["amount_deviation_score", "transaction_velocity", "failed_attempts_last_24h"]


def line(c="=", n=78):
    print(c * n)


def build_preprocessor(cat_cols, num_cols):
    cat_pipeline = Pipeline([
        ("impute", SimpleImputer(strategy="most_frequent")),
        ("encode", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1,
                                   encoded_missing_value=-2)),
    ])
    num_pipeline = Pipeline([("impute", SimpleImputer(strategy="median"))])
    return ColumnTransformer(
        transformers=[("cat", cat_pipeline, cat_cols), ("num", num_pipeline, num_cols)],
        remainder="drop", verbose_feature_names_out=False,
    )


def monotone_tuple(feature_names):
    return tuple(1 if f in BEHAVIORAL_FEATURES else 0 for f in feature_names)


def sweep_thresholds(y_test, y_proba, thresholds=np.arange(0.05, 0.51, 0.05)):
    rows = []
    for t in thresholds:
        y_pred_t = (y_proba >= t).astype(int)
        cm = confusion_matrix(y_test, y_pred_t)
        tn, fp, fn, tp = cm.ravel()
        rows.append({
            "threshold": round(float(t), 2),
            "precision": float(precision_score(y_test, y_pred_t, zero_division=0)),
            "recall": float(recall_score(y_test, y_pred_t, zero_division=0)),
            "f1": float(f1_score(y_test, y_pred_t, zero_division=0)),
            "tp": int(tp), "fp": int(fp), "fn": int(fn), "tn": int(tn),
        })
    return rows


def score_ensemble_dataframe(records, threshold_override=None):
    """Scores a list-of-dicts through fraud_model.score() using whatever is
    CURRENTLY monkeypatched into fraud_model._state (see swap_ps_state below).
    threshold_override lets us force every model to be judged at the SAME
    deployed threshold (0.30) rather than each variant's own state threshold."""
    n = len(records)
    ensemble_scores = np.empty(n, dtype=float)
    paysense_scores = np.full(n, np.nan, dtype=float)
    lr_scores = np.full(n, np.nan, dtype=float)
    rules_scores = np.empty(n, dtype=float)
    t0 = time.time()
    for i, rec in enumerate(records):
        clean = {k: (None if isinstance(v, float) and np.isnan(v) else v) for k, v in rec.items()}
        result = fraud_model.score(clean)
        ensemble_scores[i] = result.ensemble_score
        if result.paysense_score is not None:
            paysense_scores[i] = result.paysense_score
        if result.light_lr_score is not None:
            lr_scores[i] = result.light_lr_score
        rules_scores[i] = result.rules_score
        if i and i % 10000 == 0:
            print(f"    ... {i:,} / {n:,} rows scored ({time.time()-t0:.1f}s elapsed)")
    elapsed = time.time() - t0
    print(f"    scored {n:,} rows in {elapsed:.1f}s ({n/max(elapsed,1e-9):.0f} rows/sec)")
    thr = threshold_override if threshold_override is not None else fraud_model.get_state().ps_threshold
    return {
        "ensemble_scores": ensemble_scores,
        "paysense_scores": paysense_scores,
        "lr_scores": lr_scores,
        "rules_scores": rules_scores,
        "threshold_used": thr,
    }


class swap_ps_state:
    """Context manager: temporarily monkeypatches the in-process
    fraud_model._state PaySense fields (model/preprocessor/features/threshold)
    to a candidate artifact, restoring the previous (frozen) state on exit.
    Never touches fraud_model.py's file-path constants or any file on disk --
    this is purely an in-memory swap for scoring purposes."""

    def __init__(self, model, prep, features, threshold=DEPLOYED_THRESHOLD):
        self.model, self.prep, self.features, self.threshold = model, prep, features, threshold
        self._saved = None

    def __enter__(self):
        st = fraud_model.get_state()
        self._saved = (st.ps_model, st.ps_prep, st.ps_features, st.ps_threshold)
        st.ps_model, st.ps_prep, st.ps_features, st.ps_threshold = (
            self.model, self.prep, self.features, self.threshold,
        )
        return st

    def __exit__(self, *exc):
        st = fraud_model.get_state()
        st.ps_model, st.ps_prep, st.ps_features, st.ps_threshold = self._saved
        return False


def metrics_from_scores(y, scores, threshold):
    preds = (scores >= threshold).astype(int)
    roc_auc = roc_auc_score(y, scores)
    pr_auc = average_precision_score(y, scores)
    cm = confusion_matrix(y, preds)
    tn, fp, fn, tp = cm.ravel() if cm.shape == (2, 2) else (None, None, None, None)
    return {
        "roc_auc": float(roc_auc), "pr_auc": float(pr_auc),
        "confusion_matrix": cm.tolist(),
        "tp": int(tp) if tp is not None else None, "fp": int(fp) if fp is not None else None,
        "fn": int(fn) if fn is not None else None, "tn": int(tn) if tn is not None else None,
        "recall": float(recall_score(y, preds, zero_division=0)),
        "precision": float(precision_score(y, preds, zero_division=0)),
        "max_score": float(np.nanmax(scores)),
        "n": int(len(y)), "n_fraud": int(np.sum(y)),
    }


def main():
    results = {}

    # ════════════════════════════════════════════════════════════════════
    #  STEP 0 — Reproduce paysense_phase3.py Block 0 split exactly
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print("STEP 0 | Reproducing paysense_phase3.py Block 0 (split + preprocessing)")
    line("=")

    master_df = pd.read_csv(MASTER_CSV)
    master_df = master_df.drop(columns=DROP_COLS)
    X_master = master_df.drop(columns=[TARGET])
    y_master = master_df[TARGET].astype(int)

    X_train_raw, X_test_raw, y_train, y_test = train_test_split(
        X_master, y_master, test_size=0.20, random_state=RANDOM_STATE, stratify=y_master
    )
    assert int(y_test.sum()) == 253, f"Canonical test fraud count drifted: {int(y_test.sum())}"
    print(f"Canonical split confirmed: train={X_train_raw.shape}, test={X_test_raw.shape}, "
          f"fraud in test={int(y_test.sum())}/253")

    CAT_COLS = X_train_raw.select_dtypes(include=["object"]).columns.tolist()
    NUM_COLS = X_train_raw.select_dtypes(include=[np.number]).columns.tolist()
    FEATURE_NAMES = CAT_COLS + NUM_COLS

    # Baseline (frozen) artifacts -- loaded read-only, NEVER modified.
    frozen_model = joblib.load(os.path.join(ARTEFACTS_DIR, "paysense_model.pkl"))
    frozen_prep = joblib.load(os.path.join(ARTEFACTS_DIR, "paysense_preprocessor.pkl"))
    frozen_features = joblib.load(os.path.join(ARTEFACTS_DIR, "paysense_feature_names.pkl"))
    X_test_frozen_proc = frozen_prep.transform(X_test_raw)
    assert list(frozen_features) == FEATURE_NAMES, "Feature order mismatch vs frozen artifact."
    y_proba_baseline_test = frozen_model.predict_proba(X_test_frozen_proc)[:, 1]
    baseline_test_metrics = metrics_from_scores(y_test.values, y_proba_baseline_test, DEPLOYED_THRESHOLD)
    baseline_test_metrics["roc_auc_full"] = float(roc_auc_score(y_test, y_proba_baseline_test))
    print(f"Baseline (frozen model) canonical test @ tau={DEPLOYED_THRESHOLD}: "
          f"ROC-AUC={baseline_test_metrics['roc_auc']:.4f} "
          f"recall={baseline_test_metrics['recall']:.4f} "
          f"precision={baseline_test_metrics['precision']:.4f}")
    results["baseline_canonical_test"] = baseline_test_metrics
    results["baseline_canonical_test_sweep"] = sweep_thresholds(y_test, y_proba_baseline_test)

    # ════════════════════════════════════════════════════════════════════
    #  STEP 1 — Generate the independently-seeded BLEND synthetic dataset
    #  (SEED=445566, disjoint from the held-out SEED=918273 dataset already
    #  on disk). Same generator function/structure, different random draw.
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print(f"STEP 1 | Generating blend synthetic dataset (seed={BLEND_SEED}, n={BLEND_N_TXN:,})")
    line("=")

    df_blend = gen_synth.generate(n_txn=BLEND_N_TXN, seed=BLEND_SEED, target_fraud_rate=0.04)
    df_blend.to_csv(BLEND_SYNTH_CSV, index=False)
    n_fraud_blend = int(df_blend["is_fraud"].sum())
    print(f"Blend dataset: {len(df_blend):,} rows, {n_fraud_blend:,} fraud "
          f"({n_fraud_blend/len(df_blend)*100:.2f}%) -- saved to {BLEND_SYNTH_CSV}")

    assert os.path.exists(HELD_OUT_SYNTH_CSV), (
        f"{HELD_OUT_SYNTH_CSV} (seed 918273) not found -- required as the held-out "
        f"synthetic evaluation set. Run generate_grounded_synthetic_dataset.py first."
    )
    df_held_out = pd.read_csv(HELD_OUT_SYNTH_CSV)
    # Disjointness check: transaction_id is NOT a valid signal here -- both
    # generator calls number rows sequentially from 0 regardless of seed
    # (transaction_id = f"SGT{idx:07d}" for idx in range(n_txn)), so the id
    # strings legitimately collide between the two files even though every
    # other column is an independent draw from a different seed. The real
    # leakage question is whether any FULL ROW (all generated content, not
    # just the arbitrary sequential id) is duplicated across the two files --
    # that would indicate the RNG streams weren't actually independent.
    compare_cols = [c for c in df_blend.columns if c != "transaction_id"]
    blend_rows = set(map(tuple, df_blend[compare_cols].astype(str).values.tolist()))
    held_out_rows = set(map(tuple, df_held_out[compare_cols].astype(str).values.tolist()))
    row_overlap = blend_rows & held_out_rows
    assert not row_overlap, (
        f"Blend (seed={BLEND_SEED}) and held-out (seed={HELD_OUT_SEED}) synthetic "
        f"sets share {len(row_overlap)} fully-identical rows -- the two seeds are "
        f"not actually producing independent draws."
    )
    print(f"Held-out synthetic set (seed={HELD_OUT_SEED}): {len(df_held_out):,} rows -- "
          f"confirmed 0 full-row duplicates with the blend set (seed={BLEND_SEED}); "
          f"transaction_id strings themselves DO collide by design (both generators "
          f"number rows sequentially from 0 regardless of seed) but that column is "
          f"dropped before training (DROP_COLS) and is not used as an identity key "
          f"anywhere in this script.")
    results["blend_dataset"] = {
        "seed": BLEND_SEED, "n_rows": len(df_blend), "n_fraud": n_fraud_blend,
        "fraud_rate": n_fraud_blend / len(df_blend),
    }
    results["held_out_synthetic_dataset"] = {
        "seed": HELD_OUT_SEED, "n_rows": len(df_held_out),
        "n_fraud": int(df_held_out["is_fraud"].sum()),
        "note": "Pre-existing file from SYNTHETIC_GROUNDING.md -- never trained on, here or before.",
    }

    # ════════════════════════════════════════════════════════════════════
    #  STEP 2 — Variant A: blended training data (original 80% train +
    #  blend synthetic), fresh preprocessor + model, monotone_constraints
    #  kept (matching the deployed model -- not regressing that fix).
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print("STEP 2 | Variant A -- blended training data")
    line("=")

    X_blend = df_blend.drop(columns=DROP_COLS + [TARGET])
    y_blend = df_blend[TARGET].astype(int)
    # Column order must match X_train_raw exactly before concatenation.
    X_blend = X_blend[X_train_raw.columns]

    X_train_A_raw = pd.concat([X_train_raw, X_blend], ignore_index=True)
    y_train_A = pd.concat([y_train.reset_index(drop=True), y_blend.reset_index(drop=True)], ignore_index=True)
    print(f"Variant A training data: {len(X_train_raw):,} original + {len(X_blend):,} blend "
          f"= {len(X_train_A_raw):,} rows before SMOTE "
          f"({int(y_train_A.sum()):,} fraud, {y_train_A.mean()*100:.2f}%)")

    CAT_COLS_A = X_train_A_raw.select_dtypes(include=["object"]).columns.tolist()
    NUM_COLS_A = X_train_A_raw.select_dtypes(include=[np.number]).columns.tolist()
    FEATURE_NAMES_A = CAT_COLS_A + NUM_COLS_A
    assert set(FEATURE_NAMES_A) == set(FEATURE_NAMES), "Variant A feature set differs from baseline's 40."

    prep_A = build_preprocessor(CAT_COLS_A, NUM_COLS_A)
    prep_A.fit(X_train_A_raw)
    X_train_A_proc = prep_A.transform(X_train_A_raw)
    X_test_A_proc = prep_A.transform(X_test_raw)  # canonical test set, own preprocessor

    smote = SMOTE(sampling_strategy="auto", k_neighbors=5, random_state=RANDOM_STATE)
    X_train_A_bal, y_train_A_bal = smote.fit_resample(X_train_A_proc, y_train_A.values)
    print(f"After SMOTE: {X_train_A_bal.shape}")

    kwargs_A = dict(BASE_XGB_KWARGS)
    kwargs_A["monotone_constraints"] = monotone_tuple(FEATURE_NAMES_A)
    model_A = XGBClassifier(**kwargs_A)
    print("Training Variant A ... ", end="", flush=True)
    model_A.fit(X_train_A_bal, y_train_A_bal, eval_set=[(X_test_A_proc, y_test)], verbose=False)
    print("done.")

    joblib.dump(model_A, os.path.join(ARTEFACTS_DIR, "paysense_model_blended_training.pkl"))
    joblib.dump(prep_A, os.path.join(ARTEFACTS_DIR, "paysense_preprocessor_blended_training.pkl"))
    joblib.dump(FEATURE_NAMES_A, os.path.join(ARTEFACTS_DIR, "paysense_feature_names_blended_training.pkl"))
    print("Saved -> paysense_model_blended_training.pkl / paysense_preprocessor_blended_training.pkl")

    y_proba_A_test = model_A.predict_proba(X_test_A_proc)[:, 1]
    variant_A_test_metrics = metrics_from_scores(y_test.values, y_proba_A_test, DEPLOYED_THRESHOLD)
    variant_A_test_metrics["roc_auc_full"] = float(roc_auc_score(y_test, y_proba_A_test))
    print(f"Variant A canonical test @ tau={DEPLOYED_THRESHOLD}: "
          f"ROC-AUC={variant_A_test_metrics['roc_auc']:.4f} "
          f"recall={variant_A_test_metrics['recall']:.4f} "
          f"precision={variant_A_test_metrics['precision']:.4f}")
    results["variant_A_canonical_test"] = variant_A_test_metrics
    results["variant_A_canonical_test_sweep"] = sweep_thresholds(y_test, y_proba_A_test)

    # ════════════════════════════════════════════════════════════════════
    #  STEP 3 — Variant B: heavier regularization, ORIGINAL data only.
    #  Same preprocessor-fitting procedure as Block 0 (fit on X_train_raw
    #  only) -- functionally identical to the frozen preprocessor, only the
    #  model hyperparameters differ from baseline.
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print("STEP 3 | Variant B -- heavier regularization, original data only")
    line("=")

    prep_B = build_preprocessor(CAT_COLS, NUM_COLS)
    prep_B.fit(X_train_raw)
    X_train_B_proc = prep_B.transform(X_train_raw)
    X_test_B_proc = prep_B.transform(X_test_raw)
    assert np.allclose(X_test_B_proc, X_test_frozen_proc), (
        "Variant B's rebuilt preprocessor disagrees with the frozen one on the test set."
    )

    X_train_B_bal, y_train_B_bal = smote.fit_resample(X_train_B_proc, y_train.values)

    kwargs_B = dict(BASE_XGB_KWARGS)
    kwargs_B.update(VARIANT_B_XGB_OVERRIDES)
    kwargs_B["monotone_constraints"] = monotone_tuple(FEATURE_NAMES)
    print(f"Variant B overrides vs. baseline: {VARIANT_B_XGB_OVERRIDES}")
    model_B = XGBClassifier(**kwargs_B)
    print("Training Variant B ... ", end="", flush=True)
    model_B.fit(X_train_B_bal, y_train_B_bal, eval_set=[(X_test_B_proc, y_test)], verbose=False)
    print("done.")

    joblib.dump(model_B, os.path.join(ARTEFACTS_DIR, "paysense_model_regularized.pkl"))
    print("Saved -> paysense_model_regularized.pkl (reuses the frozen preprocessor's fitting procedure)")

    y_proba_B_test = model_B.predict_proba(X_test_B_proc)[:, 1]
    variant_B_test_metrics = metrics_from_scores(y_test.values, y_proba_B_test, DEPLOYED_THRESHOLD)
    variant_B_test_metrics["roc_auc_full"] = float(roc_auc_score(y_test, y_proba_B_test))
    print(f"Variant B canonical test @ tau={DEPLOYED_THRESHOLD}: "
          f"ROC-AUC={variant_B_test_metrics['roc_auc']:.4f} "
          f"recall={variant_B_test_metrics['recall']:.4f} "
          f"precision={variant_B_test_metrics['precision']:.4f}")
    results["variant_B_canonical_test"] = variant_B_test_metrics
    results["variant_B_canonical_test_sweep"] = sweep_thresholds(y_test, y_proba_B_test)

    # ════════════════════════════════════════════════════════════════════
    #  STEP 4 — Ensemble-path evaluation (src.fraud_model.score()) on the
    #  held-out synthetic set (seed 918273) for A and B. Baseline's number
    #  is cited verbatim from SYNTHETIC_GROUNDING.md (already computed
    #  against this exact file) -- not re-run.
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print("STEP 4 | Ensemble-path evaluation -- held-out synthetic set (seed 918273)")
    line("=")

    print("Loading production ensemble state (frozen light_lr + rules; PaySense "
          "slot will be monkeypatched per-variant below) ...")
    fraud_model.load_artefacts()
    assert "light_lr" in fraud_model.get_state().active_scorers, "light_lr must be active."

    y_held_out = df_held_out["is_fraud"].astype(int).to_numpy()
    records_held_out = df_held_out.to_dict(orient="records")

    print(f"\nScoring held-out synthetic set through Variant A's ensemble ({len(records_held_out):,} rows) ...")
    with swap_ps_state(model_A, prep_A, FEATURE_NAMES_A, threshold=DEPLOYED_THRESHOLD):
        scored_A_synth = score_ensemble_dataframe(records_held_out)
    metrics_A_synth = metrics_from_scores(y_held_out, scored_A_synth["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Variant A: ROC-AUC={metrics_A_synth['roc_auc']:.4f} PR-AUC={metrics_A_synth['pr_auc']:.4f} "
          f"recall={metrics_A_synth['recall']:.4f} TP={metrics_A_synth['tp']}/{metrics_A_synth['n_fraud']}")
    results["variant_A_held_out_synthetic_ensemble"] = metrics_A_synth

    print(f"\nScoring held-out synthetic set through Variant B's ensemble ({len(records_held_out):,} rows) ...")
    with swap_ps_state(model_B, prep_B, FEATURE_NAMES, threshold=DEPLOYED_THRESHOLD):
        scored_B_synth = score_ensemble_dataframe(records_held_out)
    metrics_B_synth = metrics_from_scores(y_held_out, scored_B_synth["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Variant B: ROC-AUC={metrics_B_synth['roc_auc']:.4f} PR-AUC={metrics_B_synth['pr_auc']:.4f} "
          f"recall={metrics_B_synth['recall']:.4f} TP={metrics_B_synth['tp']}/{metrics_B_synth['n_fraud']}")
    results["variant_B_held_out_synthetic_ensemble"] = metrics_B_synth

    # Baseline number, cited verbatim from SYNTHETIC_GROUNDING.md §5.1 (full
    # ensemble column, monotonic-constraints model, @ threshold 0.30):
    results["baseline_held_out_synthetic_ensemble_CITED_VERBATIM"] = {
        "source": "SYNTHETIC_GROUNDING.md §5.1 (recomputed 2026-08-23 against the monotonic model)",
        "roc_auc": 0.7000, "pr_auc": 0.1015,
        "tp": 359, "fp": 2879, "fn": 626, "tn": 21136,
        "recall": 359 / 985, "precision": 0.1109,
        "n": 25000, "n_fraud": 985,
    }

    # ════════════════════════════════════════════════════════════════════
    #  STEP 5 — Ensemble-path evaluation on real Dataset 1 (74,917 rows).
    #  Baseline cited verbatim from GENERALIZATION_CHECK.md §4.4.
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print("STEP 5 | Ensemble-path evaluation -- real Dataset 1 (upi_fraud_dataset.csv)")
    print("        Only 6/40 features are honestly mappable (GENERALIZATION_CHECK.md")
    print("        §3.1, reused verbatim -- not re-derived). Never trained on by anything.")
    line("=")

    mapped1, y1, stats1 = load_dataset_1()
    # IMPORTANT: do NOT reindex to the full 40-feature schema here. The
    # original generalization_check_ensemble.py passes the mapped frame's
    # dict AS-IS (only the honestly-mapped columns as keys; every other
    # feature simply ABSENT from txn_dict, exactly as a real caller who
    # never sent those fields would produce). _score_paysense() internally
    # reindexes against whichever ps_features is currently swapped in, so a
    # single un-reindexed records1 works correctly for every variant.
    # Reindexing here would instead make the 34 unmapped columns explicit
    # None values -- which crashes src/fraud_model.py's _score_rules() at
    # `txn_dict.get("failed_attempts_last_24h", 0) > 2`, since .get()'s
    # default only applies when a key is ABSENT, not when it is present
    # with an explicit None (the same class of bug already fixed in
    # _score_light_lr but not in _score_rules -- discovered by this script
    # hitting it, see the write-up).
    records1 = mapped1.to_dict(orient="records")
    print(f"Dataset 1: {stats1['n_rows']:,} rows, {stats1['fraud_rate']*100:.2f}% fraud, "
          f"mapped columns: {stats1['features_mapped_names']}")

    print(f"\nScoring Dataset 1 through Variant A's ensemble ({len(records1):,} rows) ...")
    with swap_ps_state(model_A, prep_A, FEATURE_NAMES_A, threshold=DEPLOYED_THRESHOLD):
        scored_A_d1 = score_ensemble_dataframe(records1)
    metrics_A_d1 = metrics_from_scores(y1.to_numpy(), scored_A_d1["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Variant A: ROC-AUC={metrics_A_d1['roc_auc']:.4f} PR-AUC={metrics_A_d1['pr_auc']:.4f} "
          f"TP={metrics_A_d1['tp']}/{metrics_A_d1['n_fraud']}")
    results["variant_A_dataset1_ensemble"] = metrics_A_d1

    print(f"\nScoring Dataset 1 through Variant B's ensemble ({len(records1):,} rows) ...")
    with swap_ps_state(model_B, prep_B, FEATURE_NAMES, threshold=DEPLOYED_THRESHOLD):
        scored_B_d1 = score_ensemble_dataframe(records1)
    metrics_B_d1 = metrics_from_scores(y1.to_numpy(), scored_B_d1["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Variant B: ROC-AUC={metrics_B_d1['roc_auc']:.4f} PR-AUC={metrics_B_d1['pr_auc']:.4f} "
          f"TP={metrics_B_d1['tp']}/{metrics_B_d1['n_fraud']}")
    results["variant_B_dataset1_ensemble"] = metrics_B_d1

    results["baseline_dataset1_ensemble_CITED_VERBATIM"] = {
        "source": "GENERALIZATION_CHECK.md §4.4 (monotonic model, full ensemble, @ threshold 0.30)",
        "roc_auc": 0.7919, "pr_auc": 0.3767,
        "tp": 0, "fp": 0, "fn": 701, "tn": 74216,
        "recall": 0.0, "precision": 0.0,
        "n": 74917, "n_fraud": 701,
    }

    # ════════════════════════════════════════════════════════════════════
    #  STEP 6 — Ensemble-path evaluation on real Dataset 3 (1,000 rows,
    #  64 fraud, low power). No prior ensemble-path number exists for this
    #  dataset in any document -- computed fresh for baseline+A+B here, so
    #  all three are directly comparable (unlike Dataset 1 / held-out
    #  synthetic, where the baseline number is cited verbatim from an
    #  existing doc).
    # ════════════════════════════════════════════════════════════════════
    line("=")
    print("STEP 6 | Ensemble-path evaluation -- real Dataset 3 (low power, 64 fraud)")
    line("=")

    mapped3, y3, stats3 = load_dataset_3()
    # Same reasoning as Dataset 1 above: do NOT reindex to the full 40-feature
    # schema -- pass the mapped frame's dict as-is so unmapped features are
    # ABSENT (not explicit None), matching the original check's methodology
    # and avoiding the _score_rules() None-vs-absent crash.
    records3 = mapped3.to_dict(orient="records")
    print(f"Dataset 3: {stats3['n_rows']:,} rows, {stats3['fraud_rate']*100:.2f}% fraud, "
          f"mapped columns: {stats3['features_mapped_names']}")

    with swap_ps_state(frozen_model, frozen_prep, list(frozen_features), threshold=DEPLOYED_THRESHOLD):
        scored_baseline_d3 = score_ensemble_dataframe(records3)
    metrics_baseline_d3 = metrics_from_scores(y3.to_numpy(), scored_baseline_d3["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Baseline : ROC-AUC={metrics_baseline_d3['roc_auc']:.4f} PR-AUC={metrics_baseline_d3['pr_auc']:.4f} "
          f"TP={metrics_baseline_d3['tp']}/{metrics_baseline_d3['n_fraud']}")
    results["baseline_dataset3_ensemble"] = metrics_baseline_d3

    with swap_ps_state(model_A, prep_A, FEATURE_NAMES_A, threshold=DEPLOYED_THRESHOLD):
        scored_A_d3 = score_ensemble_dataframe(records3)
    metrics_A_d3 = metrics_from_scores(y3.to_numpy(), scored_A_d3["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Variant A: ROC-AUC={metrics_A_d3['roc_auc']:.4f} PR-AUC={metrics_A_d3['pr_auc']:.4f} "
          f"TP={metrics_A_d3['tp']}/{metrics_A_d3['n_fraud']}")
    results["variant_A_dataset3_ensemble"] = metrics_A_d3

    with swap_ps_state(model_B, prep_B, FEATURE_NAMES, threshold=DEPLOYED_THRESHOLD):
        scored_B_d3 = score_ensemble_dataframe(records3)
    metrics_B_d3 = metrics_from_scores(y3.to_numpy(), scored_B_d3["ensemble_scores"], DEPLOYED_THRESHOLD)
    print(f"  Variant B: ROC-AUC={metrics_B_d3['roc_auc']:.4f} PR-AUC={metrics_B_d3['pr_auc']:.4f} "
          f"TP={metrics_B_d3['tp']}/{metrics_B_d3['n_fraud']}")
    results["variant_B_dataset3_ensemble"] = metrics_B_d3

    # ════════════════════════════════════════════════════════════════════
    #  Save results JSON
    # ════════════════════════════════════════════════════════════════════
    out_path = os.path.join(BASE_DIR, "ood_generalization_remediation_results.json")
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\nResults saved -> {out_path}")

    line("=")
    print("DONE")
    line("=")
    return results


if __name__ == "__main__":
    main()
